apiVersion: v1
kind: Service
metadata:
  name: backend-service-clusterip
  namespace: sentiment-analysis-mlops
spec:
  selector:
    env: production-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
