apiVersion: v1
kind: Service
metadata:
  name: frontend-service-loadbalancer
  namespace: sentiment-analysis-mlops
spec:
  selector:
    env: production-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
